all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: aws.pem
    service_subnet: "172.32.0.0/16"
    pod_subnet: "10.244.0.0/16"
  hosts:
    master:
      ansible_host: 10.1.15.177
    workers:
      ansible_host: 10.1.1.243
